# Generated by Django 4.2.7 on 2025-06-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ui_ux', 'UI/UX Design'), ('consulting', 'IT Consulting'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ui_ux', 'UI/UX Design'), ('consulting', 'IT Consulting'), ('other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
