services:
  # Backend service
  - type: web
    name: coregenesis-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn coregenesis.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://coregenesis-frontend.onrender.com

  # Frontend service
  - type: web
    name: coregenesis-frontend
    env: node
    buildCommand: cd project && npm install && npm run build
    startCommand: cd project && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://coregenesis-backend.onrender.com 